### ISSUE TITLE
build instructions

### ISSUE THREAD

**Issue by drom** [circt/handshake#1]
@stephenneuendorffer I love the idea of `handshake` MLIR dialect!
Could you please describe the steps to build it?
I assume it should be close to https://reviews.llvm.org/D77133 ?

**Comment by stephenneuendorffer** [comment]
Currently you will also need https://reviews.llvm.org/D80358.
Then after building LLVM with LLVM_ENABLE_PROJECTS=mlir, you can compile along the lines of the standalone example.  e.g.: 

```
mkdir build; cd build
cmake -GNinja \
                -DLLVM_DIR=${LLVM_BUILD_DIR}/lib/cmake/llvm \
                -DMLIR_DIR=${LLVM_BUILD_DIR}/lib/cmake/mlir ..
```
